/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 345341119
 */
public class MainMenu extends javax.swing.JFrame {

    public static EthicsCase [] cases = new EthicsCase [8];
           
    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        
        cases[0]= new PrivacyCase(
         "The Always-On Microphone" ,
           "A smart speaker company recorded household conversations even" +
           "\nwhen the device was not activated. Employees reviewed the recordings.",
           "\nAudio Recordings"
           );
        cases[1]= new AlgorithmCase(
        "The Biased Hiring Bot" ,
        "A tech company's AI screening tool ranked male applicants higher" +
        "than equally qualified female applicants." ,
        "gender bias"
        );
        cases[2] = new MisinformationCase(
        "The Deepfake Politician" ,
        "A deepfake video of a candidate saying things they never said spread" +
        "widely online during an election before being identified as fake." ,
        "deepfake video"
        );
        
        cases[3]= new IntellectualPropertyCase(
        "AI Trained on Artist Work",
        "An AI image generator was trained on millions of artworks scraped" +
        "without permission. Artists receive no credit or payment. "  ,
        "AI-generated art"
        );
        
        cases[4] = new PrivacyCase(
        " The School Laptop Spyware" ,
        "A school installed monitoring software on student laptops that" +
        "secretly activated webcams and tracked student activity at home" + 
        "without students knowing. Parents later raised concerns about privacy" + 
        "and surveillance." ,
        "webcam monitoring"
        );
        
        cases[5] = new AlgorithmCase(
         "The Loan Approval System",
         "A bank used an AI system to decide loan approvals. The system rejected" + 
         "applicants from lower-income neighbourhoods more often, even when they" + 
         "had strong credit scores and stable jobs." ,
         "income bias"       
        );
        
        cases[6] = new MisinformationCase(
       "The Edited Celebrity Clip"  ,
       "A short edited video of a celebrity appeared online and made it seem like" +
       "they insulted a group of people. The clip spread quickly before the" +
       "full unedited video revealed the statement was taken out of context." ,
       "manipulated video"         
        );
        
        cases[7] = new IntellectualPropertyCase(
        "The Copied Student Code" ,
        "A student copied large sections of another programmer’s code from GitHub" +
        "for a school project without giving credit. The project earned a high mark" +
        "before the plagiarism was discovered." ,
        "software plagiarism"        
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ethics Evaluator");

        jButton1.setText("Start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jButton1)))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 226, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Frame1().setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
